[package]
name = "xoodyak"
version = "0.1.0"
authors = ["nixberg <k.nixberg@gmail.com>"]
edition = "2018"

[dev-dependencies]
hex = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
